package gob.shcp.sireh.service.servicios;

import gob.shcp.fsn.service.AbstractService;
import gob.shcp.sireh.data.jdbc.TdEmpleadoDAO;
import gob.shcp.sireh.data.jdbc.TdPlazaDAO;
import gob.shcp.sireh.data.jdbc.TnMovtosEmpPlaDAO;
import gob.shcp.sireh.data.jdbc.servicios.QueryTdBitacoraUpdateTablaDAO;
import gob.shcp.sireh.data.jdbc.servicios.TdBitacoraUpdateTablaDAO;
import gob.shcp.sireh.domain.jdbc.TdEmpleado;
import gob.shcp.sireh.domain.jdbc.TdPlaza;
import gob.shcp.sireh.domain.jdbc.TnMovtosEmpPla;
import gob.shcp.sireh.domain.jdbc.servicios.TdBitacoraUpdateTabla;
import gob.shcp.sireh.model.nomina.TdEmpleadoDTO;
import gob.shcp.sireh.model.nomina.TnMovtosEmpPlaDTO;
import gob.shcp.sireh.model.plaza.TdPlazaDTO;
import gob.shcp.sireh.model.servicios.TablaDTO;

public class ServiciosBS extends AbstractService implements ServiciosService {

    public TdPlazaDTO getByIdTdPlaza(Integer idPlaza){
        return super.transformation().map(super.getService(TdPlazaDAO.class).getById(idPlaza), TdPlazaDTO.class);
    }
    
    public String FindByRfc(String rfc){
        TdEmpleado empleado = super.persistence().get(TdEmpleadoDAO.class).getById(rfc);
        return empleado.getNombreEmpleado() + " " + empleado.getPrimerApellido() + " " + empleado.getSegundoApellido();
    }
    
    public void salvarRegistroTdPlaza(TdPlazaDTO antesTdPlazaDTO, TdPlazaDTO despuesTdPlazaDTO, TablaDTO tablaDTO, String ip){
        TdPlaza antesTdPlaza = super.transformation().map(antesTdPlazaDTO, TdPlaza.class);
        TdPlaza despuesTdPlaza = super.transformation().map(despuesTdPlazaDTO, TdPlaza.class);
        Integer secuencia = null;
        
        super.persistence().get(TdPlazaDAO.class).save(despuesTdPlaza);
        
        
        StringBuilder antes = new StringBuilder();
        StringBuilder despues = new StringBuilder();
        StringBuilder headerTdPlaza = new StringBuilder();
        
        antes = antes.append(antesTdPlaza.getIdPlaza()).append("|");            headerTdPlaza = headerTdPlaza.append("ID_PLAZA").append("|");
        antes = antes.append(antesTdPlaza.getIdSitPlaza()).append("|");         headerTdPlaza = headerTdPlaza.append("ID_SIT_PLAZA").append("|");
        antes = antes.append(antesTdPlaza.getPlazaRfc()).append("|");           headerTdPlaza = headerTdPlaza.append("PLAZA_RFC").append("|");
        antes = antes.append(antesTdPlaza.getPlazaCiclo()).append("|");         headerTdPlaza = headerTdPlaza.append("PLAZA_CICLO").append("|");
        antes = antes.append(antesTdPlaza.getPlazaRespaldo()).append("|");      headerTdPlaza = headerTdPlaza.append("PLAZA_RESPALDO").append("|");
        antes = antes.append(antesTdPlaza.getIdGrupoPago()).append("|");        headerTdPlaza = headerTdPlaza.append("ID_GRUPO_PAGO").append("|");
        antes = antes.append(antesTdPlaza.getIdUnidadPre()).append("|");        headerTdPlaza = headerTdPlaza.append("ID_UNIDAD_PRE").append("|");
        antes = antes.append(antesTdPlaza.getIdPuestoPre()).append("|");        headerTdPlaza = headerTdPlaza.append("ID_PUESTO_PRE").append("|");
        antes = antes.append(antesTdPlaza.getIdEdoPre()).append("|");           headerTdPlaza = headerTdPlaza.append("ID_EDO_PRE").append("|");
        antes = antes.append(antesTdPlaza.getIdZonaEcoPre()).append("|");       headerTdPlaza = headerTdPlaza.append("ID_ZONA_ECO_PRE").append("|");
        antes = antes.append(antesTdPlaza.getIdRangoPre()).append("|");         headerTdPlaza = headerTdPlaza.append("ID_RANGO_PRE").append("|");
        antes = antes.append(antesTdPlaza.getIdProyReducePre()).append("|");    headerTdPlaza = headerTdPlaza.append("ID_PROY_REDUCE_PRE").append("|");
        antes = antes.append(antesTdPlaza.getIdProyAmpliaPre()).append("|");    headerTdPlaza = headerTdPlaza.append("ID_PROY_AMPLIA_PRE").append("|");
        antes = antes.append(antesTdPlaza.getIdUnidadNom()).append("|");        headerTdPlaza = headerTdPlaza.append("ID_UNIDAD_NOM").append("|");
        antes = antes.append(antesTdPlaza.getIdPuestoNom()).append("|");        headerTdPlaza = headerTdPlaza.append("ID_PUESTO_NOM").append("|");
        antes = antes.append(antesTdPlaza.getIdEdoNom()).append("|");           headerTdPlaza = headerTdPlaza.append("ID_EDO_NOM").append("|");
        antes = antes.append(antesTdPlaza.getIdMuniNom()).append("|");          headerTdPlaza = headerTdPlaza.append("ID_MUNI_NOM").append("|");
        antes = antes.append(antesTdPlaza.getIdZonaEcoNom()).append("|");       headerTdPlaza = headerTdPlaza.append("ID_ZONA_ECO_NOM").append("|");
        antes = antes.append(antesTdPlaza.getIdRangoNom()).append("|");         headerTdPlaza = headerTdPlaza.append("ID_RANGO_NOM").append("|");
        antes = antes.append(antesTdPlaza.getIdZonaDistNom()).append("|");      headerTdPlaza = headerTdPlaza.append("ID_ZONA_DIST_NOM").append("|");
        antes = antes.append(antesTdPlaza.getPlazaImpHono()).append("|");       headerTdPlaza = headerTdPlaza.append("PLAZA_IMP_HONO").append("|");
        antes = antes.append(antesTdPlaza.getIdMovtoPersona()).append("|");     headerTdPlaza = headerTdPlaza.append("ID_MOVTO_PERSONA").append("|");
        antes = antes.append(antesTdPlaza.getPlazaUltimoMovto()).append("|");   headerTdPlaza = headerTdPlaza.append("PLAZA_ULTIMO_MOVTO").append("|");
        antes = antes.append(antesTdPlaza.getPlazaIniCont()).append("|");       headerTdPlaza = headerTdPlaza.append("PLAZA_INI_CONT").append("|");
        antes = antes.append(antesTdPlaza.getPlazaFinCont()).append("|");       headerTdPlaza = headerTdPlaza.append("PLAZA_FIN_CONT").append("|");
        antes = antes.append(antesTdPlaza.getPlazaIniLic()).append("|");        headerTdPlaza = headerTdPlaza.append("PLAZA_INI_LIC").append("|");
        antes = antes.append(antesTdPlaza.getPlazaFinLic()).append("|");        headerTdPlaza = headerTdPlaza.append("PLAZA_FIN_LIC").append("|");
        antes = antes.append(antesTdPlaza.getPlazaReferencia()).append("|");    headerTdPlaza = headerTdPlaza.append("PLAZA_REFERENCIA").append("|");
        antes = antes.append(antesTdPlaza.getPlazaQnaCaptura()).append("|");    headerTdPlaza = headerTdPlaza.append("PLAZA_QNA_CAPTURA").append("|");
        antes = antes.append(antesTdPlaza.getIdTipoPlaza()).append("|");        headerTdPlaza = headerTdPlaza.append("ID_TIPO_PLAZA").append("|");
        antes = antes.append(antesTdPlaza.getIdServPub()).append("|");          headerTdPlaza = headerTdPlaza.append("ID_SERV_PUB").append("|");
        antes = antes.append(antesTdPlaza.getIdPtoEstrategico()).append("|");   headerTdPlaza = headerTdPlaza.append("ID_PTO_ESTRATEGICO").append("|");
        antes = antes.append(antesTdPlaza.getIdNodo()).append("|");             headerTdPlaza = headerTdPlaza.append("ID_NODO").append("|");
        antes = antes.append(antesTdPlaza.getIdInmueble()).append("|");         headerTdPlaza = headerTdPlaza.append("ID_INMUEBLE").append("|");
        antes = antes.append(antesTdPlaza.getPlazaEdif()).append("|");          headerTdPlaza = headerTdPlaza.append("PLAZA_EDIF").append("|");
        antes = antes.append(antesTdPlaza.getPlazaPiso()).append("|");          headerTdPlaza = headerTdPlaza.append("PLAZA_PISO").append("|");
        antes = antes.append(antesTdPlaza.getPlazaAla()).append("|");           headerTdPlaza = headerTdPlaza.append("PLAZA_ALA").append("|");
        antes = antes.append(antesTdPlaza.getPlazaOfna()).append("|");          headerTdPlaza = headerTdPlaza.append("PLAZA_OFNA").append("|");
        antes = antes.append(antesTdPlaza.getPlazaTelOf1()).append("|");        headerTdPlaza = headerTdPlaza.append("PLAZA_TEL_OF1").append("|");
        antes = antes.append(antesTdPlaza.getPlazaTelOf2()).append("|");        headerTdPlaza = headerTdPlaza.append("PLAZA_TEL_OF2").append("|");
        antes = antes.append(antesTdPlaza.getPlazaConmut()).append("|");        headerTdPlaza = headerTdPlaza.append("PLAZA_CONMUT").append("|");
        antes = antes.append(antesTdPlaza.getPlazaExt1()).append("|");          headerTdPlaza = headerTdPlaza.append("PLAZA_EXT1").append("|");
        antes = antes.append(antesTdPlaza.getPlazaExt2()).append("|");          headerTdPlaza = headerTdPlaza.append("PLAZA_EXT2").append("|");
        antes = antes.append(antesTdPlaza.getIdObligado()).append("|");         headerTdPlaza = headerTdPlaza.append("ID_OBLIGADO").append("|");
        antes = antes.append(antesTdPlaza.getIdMotivoObligado()).append("|");   headerTdPlaza = headerTdPlaza.append("ID_MOTIVO_OBLIGADO").append("|");
        antes = antes.append(antesTdPlaza.getIdVacancia()).append("|");         headerTdPlaza = headerTdPlaza.append("ID_VACANCIA").append("|");
        antes = antes.append(antesTdPlaza.getUsuario()).append("|");            headerTdPlaza = headerTdPlaza.append("USUARIO").append("|");
        antes = antes.append(antesTdPlaza.getFecModifico());                    headerTdPlaza = headerTdPlaza.append("FEC_MODIFICO");
        
        despues = despues.append(despuesTdPlaza.getIdPlaza()).append("|");      
        despues = despues.append(despuesTdPlaza.getIdSitPlaza()).append("|");   
        despues = despues.append(despuesTdPlaza.getPlazaRfc()).append("|");     
        despues = despues.append(despuesTdPlaza.getPlazaCiclo()).append("|");   
        despues = despues.append(despuesTdPlaza.getPlazaRespaldo()).append("|");
        despues = despues.append(despuesTdPlaza.getIdGrupoPago()).append("|");  
        despues = despues.append(despuesTdPlaza.getIdUnidadPre()).append("|");  
        despues = despues.append(despuesTdPlaza.getIdPuestoPre()).append("|");  
        despues = despues.append(despuesTdPlaza.getIdEdoPre()).append("|");     
        despues = despues.append(despuesTdPlaza.getIdZonaEcoPre()).append("|"); 
        despues = despues.append(despuesTdPlaza.getIdRangoPre()).append("|");   
        despues = despues.append(despuesTdPlaza.getIdProyReducePre()).append("|");
        despues = despues.append(despuesTdPlaza.getIdProyAmpliaPre()).append("|");
        despues = despues.append(despuesTdPlaza.getIdUnidadNom()).append("|");  
        despues = despues.append(despuesTdPlaza.getIdPuestoNom()).append("|");  
        despues = despues.append(despuesTdPlaza.getIdEdoNom()).append("|");     
        despues = despues.append(despuesTdPlaza.getIdMuniNom()).append("|");    
        despues = despues.append(despuesTdPlaza.getIdZonaEcoNom()).append("|"); 
        despues = despues.append(despuesTdPlaza.getIdRangoNom()).append("|");   
        despues = despues.append(despuesTdPlaza.getIdZonaDistNom()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaImpHono()).append("|"); 
        despues = despues.append(despuesTdPlaza.getIdMovtoPersona()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaUltimoMovto()).append("|"); 
        despues = despues.append(despuesTdPlaza.getPlazaIniCont()).append("|"); 
        despues = despues.append(despuesTdPlaza.getPlazaFinCont()).append("|"); 
        despues = despues.append(despuesTdPlaza.getPlazaIniLic()).append("|");  
        despues = despues.append(despuesTdPlaza.getPlazaFinLic()).append("|");  
        despues = despues.append(despuesTdPlaza.getPlazaReferencia()).append("|"); 
        despues = despues.append(despuesTdPlaza.getPlazaQnaCaptura()).append("|"); 
        despues = despues.append(despuesTdPlaza.getIdTipoPlaza()).append("|");  
        despues = despues.append(despuesTdPlaza.getIdServPub()).append("|");    
        despues = despues.append(despuesTdPlaza.getIdPtoEstrategico()).append("|"); 
        despues = despues.append(despuesTdPlaza.getIdNodo()).append("|");       
        despues = despues.append(despuesTdPlaza.getIdInmueble()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaEdif()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaPiso()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaAla()).append("|"); 
        despues = despues.append(despuesTdPlaza.getPlazaOfna()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaTelOf1()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaTelOf2()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaConmut()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaExt1()).append("|");
        despues = despues.append(despuesTdPlaza.getPlazaExt2()).append("|");
        despues = despues.append(despuesTdPlaza.getIdObligado()).append("|");
        despues = despues.append(despuesTdPlaza.getIdMotivoObligado()).append("|");
        despues = despues.append(despuesTdPlaza.getIdVacancia()).append("|");
        despues = despues.append(despuesTdPlaza.getUsuario()).append("|");
        despues = despues.append(despuesTdPlaza.getFecModifico()); 
        
        secuencia = super.persistence().get(QueryTdBitacoraUpdateTablaDAO.class).getSequenceTdBitacoraTabla().get(0).getIdBitacora();
        TdBitacoraUpdateTabla bitacora = new TdBitacoraUpdateTabla(secuencia, despues.toString(), antes.toString(), headerTdPlaza.toString(), ip, tablaDTO.getMotivoModifica(), "TD_PLAZA");
        super.persistence().get(TdBitacoraUpdateTablaDAO.class).save(bitacora);
    }
    
    public TnMovtosEmpPlaDTO getByIdTnMovtosEmpPlaza(Integer idMovtosEmpPla){
        return super.transformation().map(super.getService(TnMovtosEmpPlaDAO.class).getById(idMovtosEmpPla), TnMovtosEmpPlaDTO.class);
    }
    
    public void salvarRegistroTnMovtosEmpPlaza(TnMovtosEmpPlaDTO antesC, TnMovtosEmpPlaDTO despuesC, TablaDTO tablaDTO, String ip){
        TnMovtosEmpPla antesMep = super.transformation().map(antesC, TnMovtosEmpPla.class);
        TnMovtosEmpPla despuesMep = super.transformation().map(despuesC, TnMovtosEmpPla.class);
        
        despuesMep.setIdMovtosEmpPla(new Long(despuesC.getIdMovtosEmpPla()));
        antesMep.setIdMovtosEmpPla(new Long(antesC.getIdMovtosEmpPla()));
        super.persistence().get(TnMovtosEmpPlaDAO.class).save(despuesMep);
        
        StringBuilder antes = new StringBuilder();
        StringBuilder despues = new StringBuilder();
        StringBuilder heads = new StringBuilder();
        
        antes = antes.append(antesMep.getIdMovtosEmpPla()).append("|");
        antes = antes.append(antesMep.getIdMovtoPersona()).append("|");
        antes = antes.append(antesMep.getIdPlaza()).append("|");
        antes = antes.append(antesMep.getIdSituacionPlaza()).append("|");
        antes = antes.append(antesMep.getMepRfc()).append("|");
        antes = antes.append(antesMep.getMepPlazaRespaldo()).append("|");
        antes = antes.append(antesMep.getIdGrupoPago()).append("|");
        antes = antes.append(antesMep.getIdUnidadPre()).append("|");
        antes = antes.append(antesMep.getIdPuestoPre()).append("|");
        antes = antes.append(antesMep.getIdEdoPre()).append("|");
        antes = antes.append(antesMep.getIdZonaEcoPre()).append("|");
        antes = antes.append(antesMep.getIdRangoPre()).append("|");
        antes = antes.append(antesMep.getIdUnidadNom()).append("|");
        antes = antes.append(antesMep.getIdPuestoNom()).append("|");
        antes = antes.append(antesMep.getIdNivelPtoNom()).append("|");
        antes = antes.append(antesMep.getIdNombramientoNom()).append("|");
        antes = antes.append(antesMep.getIdJerarquiaNom()).append("|");
        antes = antes.append(antesMep.getIdEdoNom()).append("|");
        antes = antes.append(antesMep.getIdMuniNom()).append("|");
        antes = antes.append(antesMep.getIdZonaEcoNom()).append("|");
        antes = antes.append(antesMep.getIdRangoNom()).append("|");
        antes = antes.append(antesMep.getIdZonaDistNom()).append("|");
        antes = antes.append(antesMep.getMepImporteHonorario()).append("|");
        antes = antes.append(antesMep.getMepUltimoMovto()).append("|");
        antes = antes.append(antesMep.getMepIniCont()).append("|");
        antes = antes.append(antesMep.getMepFinCont()).append("|");
        antes = antes.append(antesMep.getMepIniLic()).append("|");
        antes = antes.append(antesMep.getMepFinLic()).append("|");
        antes = antes.append(antesMep.getMepQnaCaptura()).append("|");
        antes = antes.append(antesMep.getIdTipoPlaza()).append("|");
        antes = antes.append(antesMep.getIdServPub()).append("|");
        antes = antes.append(antesMep.getIdPtoEstrategico()).append("|");
        antes = antes.append(antesMep.getIdInmueble()).append("|");
        antes = antes.append(antesMep.getMepEdif()).append("|");
        antes = antes.append(antesMep.getMepPiso()).append("|");
        antes = antes.append(antesMep.getMepAla()).append("|");
        antes = antes.append(antesMep.getMepOfna()).append("|");
        antes = antes.append(antesMep.getMepTelOf1()).append("|");
        antes = antes.append(antesMep.getMepTelOf2()).append("|");
        antes = antes.append(antesMep.getMepConmut()).append("|");
        antes = antes.append(antesMep.getMepExt1()).append("|");
        antes = antes.append(antesMep.getMepExt2()).append("|");
        antes = antes.append(antesMep.getMepRfcUnico()).append("|");
        antes = antes.append(antesMep.getIdBancoSar()).append("|");
        antes = antes.append(antesMep.getIdTipoPago()).append("|");
        antes = antes.append(antesMep.getMepImssIssste()).append("|");
        antes = antes.append(antesMep.getMepSistemaReparto()).append("|");
        antes = antes.append(antesMep.getMepCurp()).append("|");
        antes = antes.append(antesMep.getMepNombre()).append("|");
        antes = antes.append(antesMep.getMepPrimerApellido()).append("|");
        antes = antes.append(antesMep.getMepSegundoApellido()).append("|");
        antes = antes.append(antesMep.getMepFecNacimiento()).append("|");
        antes = antes.append(antesMep.getMepClabe()).append("|");
        antes = antes.append(antesMep.getMepReferenciaOficio()).append("|");
        antes = antes.append(antesMep.getMepIngresoGobFed()).append("|");
        antes = antes.append(antesMep.getMepIngresoDependencia()).append("|");
        antes = antes.append(antesMep.getMepCasoMuestra()).append("|");
        antes = antes.append(antesMep.getMepCalleParticular()).append("|");
        antes = antes.append(antesMep.getMepColoniaParticular()).append("|");
        antes = antes.append(antesMep.getIdMuniParticular()).append("|");
        antes = antes.append(antesMep.getIdEdoParticular()).append("|");
        antes = antes.append(antesMep.getMepCodpostParticular()).append("|");
        antes = antes.append(antesMep.getMepTelParticular()).append("|");
        antes = antes.append(antesMep.getIdEdoCivil()).append("|");
        antes = antes.append(antesMep.getMepEMailOficial()).append("|");
        antes = antes.append(antesMep.getMepEMailPersonal()).append("|");
        antes = antes.append(antesMep.getIdEdoNac()).append("|");
        antes = antes.append(antesMep.getIdGenero()).append("|");
        antes = antes.append(antesMep.getIdNacionalidad()).append("|");
        antes = antes.append(antesMep.getMepDiscapacidad()).append("|");
        antes = antes.append(antesMep.getIdNivelEscolar()).append("|");
        antes = antes.append(antesMep.getIdProfnCarrera()).append("|");
        antes = antes.append(antesMep.getIdInstEducativa()).append("|");
        antes = antes.append(antesMep.getIdInstProtcivil()).append("|");
        antes = antes.append(antesMep.getIdEspProtcivil()).append("|");
        antes = antes.append(antesMep.getMepEstudiaSiNo()).append("|");
        antes = antes.append(antesMep.getMepPadreMadre()).append("|");
        antes = antes.append(antesMep.getMepTerminoCargoSind()).append("|");
        antes = antes.append(antesMep.getMepCompatEmpleo()).append("|");
        antes = antes.append(antesMep.getIdRusp()).append("|");
        antes = antes.append(antesMep.getMepFecNotDecPatr()).append("|");
        antes = antes.append(antesMep.getMepFecIniDeclPatr()).append("|");
        antes = antes.append(antesMep.getMepFecIngSpc()).append("|");
        antes = antes.append(antesMep.getMepSpcAnioAnt()).append("|");
        antes = antes.append(antesMep.getIdUnidadNomAnt()).append("|");
        antes = antes.append(antesMep.getIdPuestoNomAnt()).append("|");
        antes = antes.append(antesMep.getIdEdoNomAnt()).append("|");
        antes = antes.append(antesMep.getIdMuniNomAnt()).append("|");
        antes = antes.append(antesMep.getIdZonaEcoNomAnt()).append("|");
        antes = antes.append(antesMep.getIdRangoNomAnt()).append("|");
        antes = antes.append(antesMep.getIdNombramientoAnt()).append("|");
        antes = antes.append(antesMep.getMepPlazaAnt()).append("|");
        antes = antes.append(antesMep.getIdNivelPtoAnt()).append("|");
        antes = antes.append(antesMep.getIdJerarquiaAnt()).append("|");
        antes = antes.append(antesMep.getMepObserva()).append("|");
        antes = antes.append(antesMep.getMepObservaInternas()).append("|");
        antes = antes.append(antesMep.getMepQnaCancela()).append("|");
        antes = antes.append(antesMep.getMepUsrCancela()).append("|");
        antes = antes.append(antesMep.getMepFechaCancela()).append("|");
        antes = antes.append(antesMep.getUsuario()).append("|");
        antes = antes.append(antesMep.getFecModifico());
        
        despues = despues.append(despuesMep.getIdMovtosEmpPla()).append("|");
        despues = despues.append(despuesMep.getIdMovtoPersona()).append("|");
        despues = despues.append(despuesMep.getIdPlaza()).append("|");
        despues = despues.append(despuesMep.getIdSituacionPlaza()).append("|");
        despues = despues.append(despuesMep.getMepRfc()).append("|");
        despues = despues.append(despuesMep.getMepPlazaRespaldo()).append("|");
        despues = despues.append(despuesMep.getIdGrupoPago()).append("|");
        despues = despues.append(despuesMep.getIdUnidadPre()).append("|");
        despues = despues.append(despuesMep.getIdPuestoPre()).append("|");
        despues = despues.append(despuesMep.getIdEdoPre()).append("|");
        despues = despues.append(despuesMep.getIdZonaEcoPre()).append("|");
        despues = despues.append(despuesMep.getIdRangoPre()).append("|");
        despues = despues.append(despuesMep.getIdUnidadNom()).append("|");
        despues = despues.append(despuesMep.getIdPuestoNom()).append("|");
        despues = despues.append(despuesMep.getIdNivelPtoNom()).append("|");
        despues = despues.append(despuesMep.getIdNombramientoNom()).append("|");
        despues = despues.append(despuesMep.getIdJerarquiaNom()).append("|");
        despues = despues.append(despuesMep.getIdEdoNom()).append("|");
        despues = despues.append(despuesMep.getIdMuniNom()).append("|");
        despues = despues.append(despuesMep.getIdZonaEcoNom()).append("|");
        despues = despues.append(despuesMep.getIdRangoNom()).append("|");
        despues = despues.append(despuesMep.getIdZonaDistNom()).append("|");
        despues = despues.append(despuesMep.getMepImporteHonorario()).append("|");
        despues = despues.append(despuesMep.getMepUltimoMovto()).append("|");
        despues = despues.append(despuesMep.getMepIniCont()).append("|");
        despues = despues.append(despuesMep.getMepFinCont()).append("|");
        despues = despues.append(despuesMep.getMepIniLic()).append("|");
        despues = despues.append(despuesMep.getMepFinLic()).append("|");
        despues = despues.append(despuesMep.getMepQnaCaptura()).append("|");
        despues = despues.append(despuesMep.getIdTipoPlaza()).append("|");
        despues = despues.append(despuesMep.getIdServPub()).append("|");
        despues = despues.append(despuesMep.getIdPtoEstrategico()).append("|");
        despues = despues.append(despuesMep.getIdInmueble()).append("|");
        despues = despues.append(despuesMep.getMepEdif()).append("|");
        despues = despues.append(despuesMep.getMepPiso()).append("|");
        despues = despues.append(despuesMep.getMepAla()).append("|");
        despues = despues.append(despuesMep.getMepOfna()).append("|");
        despues = despues.append(despuesMep.getMepTelOf1()).append("|");
        despues = despues.append(despuesMep.getMepTelOf2()).append("|");
        despues = despues.append(despuesMep.getMepConmut()).append("|");
        despues = despues.append(despuesMep.getMepExt1()).append("|");
        despues = despues.append(despuesMep.getMepExt2()).append("|");
        despues = despues.append(despuesMep.getMepRfcUnico()).append("|");
        despues = despues.append(despuesMep.getIdBancoSar()).append("|");
        despues = despues.append(despuesMep.getIdTipoPago()).append("|");
        despues = despues.append(despuesMep.getMepImssIssste()).append("|");
        despues = despues.append(despuesMep.getMepSistemaReparto()).append("|");
        despues = despues.append(despuesMep.getMepCurp()).append("|");
        despues = despues.append(despuesMep.getMepNombre()).append("|");
        despues = despues.append(despuesMep.getMepPrimerApellido()).append("|");
        despues = despues.append(despuesMep.getMepSegundoApellido()).append("|");
        despues = despues.append(despuesMep.getMepFecNacimiento()).append("|");
        despues = despues.append(despuesMep.getMepClabe()).append("|");
        despues = despues.append(despuesMep.getMepReferenciaOficio()).append("|");
        despues = despues.append(despuesMep.getMepIngresoGobFed()).append("|");
        despues = despues.append(despuesMep.getMepIngresoDependencia()).append("|");
        despues = despues.append(despuesMep.getMepCasoMuestra()).append("|");
        despues = despues.append(despuesMep.getMepCalleParticular()).append("|");
        despues = despues.append(despuesMep.getMepColoniaParticular()).append("|");
        despues = despues.append(despuesMep.getIdMuniParticular()).append("|");
        despues = despues.append(despuesMep.getIdEdoParticular()).append("|");
        despues = despues.append(despuesMep.getMepCodpostParticular()).append("|");
        despues = despues.append(despuesMep.getMepTelParticular()).append("|");
        despues = despues.append(despuesMep.getIdEdoCivil()).append("|");
        despues = despues.append(despuesMep.getMepEMailOficial()).append("|");
        despues = despues.append(despuesMep.getMepEMailPersonal()).append("|");
        despues = despues.append(despuesMep.getIdEdoNac()).append("|");
        despues = despues.append(despuesMep.getIdGenero()).append("|");
        despues = despues.append(despuesMep.getIdNacionalidad()).append("|");
        despues = despues.append(despuesMep.getMepDiscapacidad()).append("|");
        despues = despues.append(despuesMep.getIdNivelEscolar()).append("|");
        despues = despues.append(despuesMep.getIdProfnCarrera()).append("|");
        despues = despues.append(despuesMep.getIdInstEducativa()).append("|");
        despues = despues.append(despuesMep.getIdInstProtcivil()).append("|");
        despues = despues.append(despuesMep.getIdEspProtcivil()).append("|");
        despues = despues.append(despuesMep.getMepEstudiaSiNo()).append("|");
        despues = despues.append(despuesMep.getMepPadreMadre()).append("|");
        despues = despues.append(despuesMep.getMepTerminoCargoSind()).append("|");
        despues = despues.append(despuesMep.getMepCompatEmpleo()).append("|");
        despues = despues.append(despuesMep.getIdRusp()).append("|");
        despues = despues.append(despuesMep.getMepFecNotDecPatr()).append("|");
        despues = despues.append(despuesMep.getMepFecIniDeclPatr()).append("|");
        despues = despues.append(despuesMep.getMepFecIngSpc()).append("|");
        despues = despues.append(despuesMep.getMepSpcAnioAnt()).append("|");
        despues = despues.append(despuesMep.getIdUnidadNomAnt()).append("|");
        despues = despues.append(despuesMep.getIdPuestoNomAnt()).append("|");
        despues = despues.append(despuesMep.getIdEdoNomAnt()).append("|");
        despues = despues.append(despuesMep.getIdMuniNomAnt()).append("|");
        despues = despues.append(despuesMep.getIdZonaEcoNomAnt()).append("|");
        despues = despues.append(despuesMep.getIdRangoNomAnt()).append("|");
        despues = despues.append(despuesMep.getIdNombramientoAnt()).append("|");
        despues = despues.append(despuesMep.getMepPlazaAnt()).append("|");
        despues = despues.append(despuesMep.getIdNivelPtoAnt()).append("|");
        despues = despues.append(despuesMep.getIdJerarquiaAnt()).append("|");
        despues = despues.append(despuesMep.getMepObserva()).append("|");
        despues = despues.append(despuesMep.getMepObservaInternas()).append("|");
        despues = despues.append(despuesMep.getMepQnaCancela()).append("|");
        despues = despues.append(despuesMep.getMepUsrCancela()).append("|");
        despues = despues.append(despuesMep.getMepFechaCancela()).append("|");
        despues = despues.append(despuesMep.getUsuario()).append("|");
        despues = despues.append(despuesMep.getFecModifico());
        
        heads = heads.append("ID_MOVTOS_EMP_PLA").append("|");
        heads = heads.append("ID_MOVTO_PERSONA").append("|");
        heads = heads.append("ID_PLAZA").append("|");
        heads = heads.append("ID_SITUACION_PLAZA").append("|");
        heads = heads.append("MEP_RFC").append("|");
        heads = heads.append("MEP_PLAZA_RESPALDO").append("|");
        heads = heads.append("ID_GRUPO_PAGO").append("|");
        heads = heads.append("ID_UNIDAD_PRE").append("|");
        heads = heads.append("ID_PUESTO_PRE").append("|");
        heads = heads.append("ID_EDO_PRE").append("|");
        heads = heads.append("ID_ZONA_ECO_PRE").append("|");
        heads = heads.append("ID_RANGO_PRE").append("|");
        heads = heads.append("ID_UNIDAD_NOM").append("|");
        heads = heads.append("ID_PUESTO_NOM").append("|");
        heads = heads.append("ID_NIVEL_PTO_NOM").append("|");
        heads = heads.append("ID_NOMBRAMIENTO_NOM").append("|");
        heads = heads.append("ID_JERARQUIA_NOM").append("|");
        heads = heads.append("ID_EDO_NOM").append("|");
        heads = heads.append("ID_MUNI_NOM").append("|");
        heads = heads.append("ID_ZONA_ECO_NOM").append("|");
        heads = heads.append("ID_RANGO_NOM").append("|");
        heads = heads.append("ID_ZONA_DIST_NOM").append("|");
        heads = heads.append("MEP_IMPORTE_HONORARIO").append("|");
        heads = heads.append("MEP_ULTIMO_MOVTO").append("|");
        heads = heads.append("MEP_INI_CONT").append("|");
        heads = heads.append("MEP_FIN_CONT").append("|");
        heads = heads.append("MEP_INI_LIC").append("|");
        heads = heads.append("MEP_FIN_LIC").append("|");
        heads = heads.append("MEP_QNA_CAPTURA").append("|");
        heads = heads.append("ID_TIPO_PLAZA").append("|");
        heads = heads.append("ID_SERV_PUB").append("|");
        heads = heads.append("ID_PTO_ESTRATEGICO").append("|");
        heads = heads.append("ID_INMUEBLE").append("|");
        heads = heads.append("MEP_EDIF").append("|");
        heads = heads.append("MEP_PISO").append("|");
        heads = heads.append("MEP_ALA").append("|");
        heads = heads.append("MEP_OFNA").append("|");
        heads = heads.append("MEP_TEL_OF1").append("|");
        heads = heads.append("MEP_TEL_OF2").append("|");
        heads = heads.append("MEP_CONMUT").append("|");
        heads = heads.append("MEP_EXT1").append("|");
        heads = heads.append("MEP_EXT2").append("|");
        heads = heads.append("MEP_RFC_UNICO").append("|");
        heads = heads.append("ID_BANCO_SAR").append("|");
        heads = heads.append("ID_TIPO_PAGO").append("|");
        heads = heads.append("MEP_IMSS_ISSSTE").append("|");
        heads = heads.append("MEP_SISTEMA_REPARTO").append("|");
        heads = heads.append("MEP_CURP").append("|");
        heads = heads.append("MEP_NOMBRE").append("|");
        heads = heads.append("MEP_PRIMER_APELLIDO").append("|");
        heads = heads.append("MEP_SEGUNDO_APELLIDO").append("|");
        heads = heads.append("MEP_FEC_NACIMIENTO").append("|");
        heads = heads.append("MEP_CLABE").append("|");
        heads = heads.append("MEP_REFERENCIA_OFICIO").append("|");
        heads = heads.append("MEP_INGRESO_GOB_FED").append("|");
        heads = heads.append("MEP_INGRESO_DEPENDENCIA").append("|");
        heads = heads.append("MEP_CASO_MUESTRA").append("|");
        heads = heads.append("MEP_CALLE_PARTICULAR").append("|");
        heads = heads.append("MEP_COLONIA_PARTICULAR").append("|");
        heads = heads.append("ID_MUNI_PARTICULAR").append("|");
        heads = heads.append("ID_EDO_PARTICULAR").append("|");
        heads = heads.append("MEP_CODPOST_PARTICULAR").append("|");
        heads = heads.append("MEP_TEL_PARTICULAR").append("|");
        heads = heads.append("ID_EDO_CIVIL").append("|");
        heads = heads.append("MEP_E_MAIL_OFICIAL").append("|");
        heads = heads.append("MEP_E_MAIL_PERSONAL").append("|");
        heads = heads.append("ID_EDO_NAC").append("|");
        heads = heads.append("ID_GENERO").append("|");
        heads = heads.append("ID_NACIONALIDAD").append("|");
        heads = heads.append("MEP_DISCAPACIDAD").append("|");
        heads = heads.append("ID_NIVEL_ESCOLAR").append("|");
        heads = heads.append("ID_PROFN_CARRERA").append("|");
        heads = heads.append("ID_INST_EDUCATIVA").append("|");
        heads = heads.append("ID_INST_PROTCIVIL").append("|");
        heads = heads.append("ID_ESP_PROTCIVIL").append("|");
        heads = heads.append("MEP_ESTUDIA_SI_NO").append("|");
        heads = heads.append("MEP_PADRE_MADRE").append("|");
        heads = heads.append("MEP_TERMINO_CARGO_SIND").append("|");
        heads = heads.append("MEP_COMPAT_EMPLEO").append("|");
        heads = heads.append("ID_RUSP").append("|");
        heads = heads.append("MEP_FEC_NOT_DEC_PATR").append("|");
        heads = heads.append("MEP_FEC_INI_DECL_PATR").append("|");
        heads = heads.append("MEP_FEC_ING_SPC").append("|");
        heads = heads.append("MEP_SPC_ANIO_ANT").append("|");
        heads = heads.append("ID_UNIDAD_NOM_ANT").append("|");
        heads = heads.append("ID_PUESTO_NOM_ANT").append("|");
        heads = heads.append("ID_EDO_NOM_ANT").append("|");
        heads = heads.append("ID_MUNI_NOM_ANT").append("|");
        heads = heads.append("ID_ZONA_ECO_NOM_ANT").append("|");
        heads = heads.append("ID_RANGO_NOM_ANT").append("|");
        heads = heads.append("ID_NOMBRAMIENTO_ANT").append("|");
        heads = heads.append("MEP_PLAZA_ANT").append("|");
        heads = heads.append("ID_NIVEL_PTO_ANT").append("|");
        heads = heads.append("ID_JERARQUIA_ANT").append("|");
        heads = heads.append("MEP_OBSERVA").append("|");
        heads = heads.append("MEP_OBSERVA_INTERNAS").append("|");
        heads = heads.append("MEP_QNA_CANCELA").append("|");
        heads = heads.append("MEP_USR_CANCELA").append("|");
        heads = heads.append("MEP_FECHA_CANCELA").append("|");
        heads = heads.append("USUARIO").append("|");
        heads = heads.append("FEC_MODIFICO");
        
        Integer secuencia = super.persistence().get(QueryTdBitacoraUpdateTablaDAO.class).getSequenceTdBitacoraTabla().get(0).getIdBitacora();
        TdBitacoraUpdateTabla tdBitacoraMep = new TdBitacoraUpdateTabla(secuencia, despues.toString(), antes.toString(), heads.toString(), ip, tablaDTO.getMotivoModifica(), "TN_MOVTOS_EMP_PLA");
        super.persistence().get(TdBitacoraUpdateTablaDAO.class).save(tdBitacoraMep);
    }
    
    public TdEmpleadoDTO getByIdTdEmpleadoDTO(String rfcEmpleado){
        return super.transformation().map(super.getService(TdEmpleadoDAO.class).getById(rfcEmpleado), TdEmpleadoDTO.class);
    }
    
    public void salvarRegistroTdEmpleado(TdEmpleadoDTO antesDTO, TdEmpleadoDTO despuesDTO, TablaDTO tablaDTO, String ip){
        TdEmpleado antesEmpl = super.transformation().map(antesDTO, TdEmpleado.class);
        TdEmpleado despuesEmpl = super.transformation().map(despuesDTO, TdEmpleado.class);
        
        super.persistence().get(TdEmpleadoDAO.class).save(despuesEmpl);
        
        StringBuilder antes = new StringBuilder();
        StringBuilder despues = new StringBuilder();
        StringBuilder heads = new StringBuilder();
        
        antes = antes.append(antesEmpl.getRfcEmpleado()).append("|");
        antes = antes.append(antesEmpl.getRfcUnico()).append("|");
        antes = antes.append(antesEmpl.getIdUltimoMovto()).append("|");
        antes = antes.append(antesEmpl.getFecUltimoMovto()).append("|");
        antes = antes.append(antesEmpl.getIdBancoSar()).append("|");
        antes = antes.append(antesEmpl.getIdTipoPago()).append("|");
        antes = antes.append(antesEmpl.getImssIssste()).append("|");
        antes = antes.append(antesEmpl.getNumIssste()).append("|");
        antes = antes.append(antesEmpl.getSistemaReparto()).append("|");
        antes = antes.append(antesEmpl.getCurpEmpleado()).append("|");
        antes = antes.append(antesEmpl.getNombreEmpleado()).append("|");
        antes = antes.append(antesEmpl.getPrimerApellido()).append("|");
        antes = antes.append(antesEmpl.getSegundoApellido()).append("|");
        antes = antes.append(antesEmpl.getFecNacimiento()).append("|");
        antes = antes.append(antesEmpl.getClabeEmpleado()).append("|");
        antes = antes.append(antesEmpl.getReferenciaOficio()).append("|");
        antes = antes.append(antesEmpl.getEmpQnaCaptura()).append("|");
        antes = antes.append(antesEmpl.getIngresoGobFed()).append("|");
        antes = antes.append(antesEmpl.getIngresoDependencia()).append("|");
        antes = antes.append(antesEmpl.getIdPlazaVigente()).append("|");
        antes = antes.append(antesEmpl.getCasoMuestra()).append("|");
        antes = antes.append(antesEmpl.getCalleParticular()).append("|");
        antes = antes.append(antesEmpl.getColoniaParticular()).append("|");
        antes = antes.append(antesEmpl.getIdMuniParticular()).append("|");
        antes = antes.append(antesEmpl.getIdEdoParticular()).append("|");
        antes = antes.append(antesEmpl.getCodpostParticular()).append("|");
        antes = antes.append(antesEmpl.getTelParticular()).append("|");
        antes = antes.append(antesEmpl.getIdEdoCivil()).append("|");
        antes = antes.append(antesEmpl.getEMailOficial()).append("|");
        antes = antes.append(antesEmpl.getEMailPersonal()).append("|");
        antes = antes.append(antesEmpl.getIdEdoNac()).append("|");
        antes = antes.append(antesEmpl.getIdGenero()).append("|");
        antes = antes.append(antesEmpl.getIdNacionalidad()).append("|");
        antes = antes.append(antesEmpl.getDiscapacidad()).append("|");
        antes = antes.append(antesEmpl.getIdNivelEscolar()).append("|");
        antes = antes.append(antesEmpl.getIdProfnCarrera()).append("|");
        antes = antes.append(antesEmpl.getIdInstEducativa()).append("|");
        antes = antes.append(antesEmpl.getIdInstProtcivil()).append("|");
        antes = antes.append(antesEmpl.getIdEspProtCivil()).append("|");
        antes = antes.append(antesEmpl.getEstudiaSiNo()).append("|");
        antes = antes.append(antesEmpl.getPadreMadre()).append("|");
        antes = antes.append(antesEmpl.getTerminoCargoSind()).append("|");
        antes = antes.append(antesEmpl.getCompatEmpleo()).append("|");
        antes = antes.append(antesEmpl.getIdRusp()).append("|");
        antes = antes.append(antesEmpl.getFecNotDecPatr()).append("|");
        antes = antes.append(antesEmpl.getFecIniDeclPatr()).append("|");
        antes = antes.append(antesEmpl.getFecIngSpc()).append("|");
        antes = antes.append(antesEmpl.getUsuario()).append("|");
        antes = antes.append(antesEmpl.getFecModifico());
        
        despues = despues.append(despuesEmpl.getRfcEmpleado()).append("|");
        despues = despues.append(despuesEmpl.getRfcUnico()).append("|");
        despues = despues.append(despuesEmpl.getIdUltimoMovto()).append("|");
        despues = despues.append(despuesEmpl.getFecUltimoMovto()).append("|");
        despues = despues.append(despuesEmpl.getIdBancoSar()).append("|");
        despues = despues.append(despuesEmpl.getIdTipoPago()).append("|");
        despues = despues.append(despuesEmpl.getImssIssste()).append("|");
        despues = despues.append(despuesEmpl.getNumIssste()).append("|");
        despues = despues.append(despuesEmpl.getSistemaReparto()).append("|");
        despues = despues.append(despuesEmpl.getCurpEmpleado()).append("|");
        despues = despues.append(despuesEmpl.getNombreEmpleado()).append("|");
        despues = despues.append(despuesEmpl.getPrimerApellido()).append("|");
        despues = despues.append(despuesEmpl.getSegundoApellido()).append("|");
        despues = despues.append(despuesEmpl.getFecNacimiento()).append("|");
        despues = despues.append(despuesEmpl.getClabeEmpleado()).append("|");
        despues = despues.append(despuesEmpl.getReferenciaOficio()).append("|");
        despues = despues.append(despuesEmpl.getEmpQnaCaptura()).append("|");
        despues = despues.append(despuesEmpl.getIngresoGobFed()).append("|");
        despues = despues.append(despuesEmpl.getIngresoDependencia()).append("|");
        despues = despues.append(despuesEmpl.getIdPlazaVigente()).append("|");
        despues = despues.append(despuesEmpl.getCasoMuestra()).append("|");
        despues = despues.append(despuesEmpl.getCalleParticular()).append("|");
        despues = despues.append(despuesEmpl.getColoniaParticular()).append("|");
        despues = despues.append(despuesEmpl.getIdMuniParticular()).append("|");
        despues = despues.append(despuesEmpl.getIdEdoParticular()).append("|");
        despues = despues.append(despuesEmpl.getCodpostParticular()).append("|");
        despues = despues.append(despuesEmpl.getTelParticular()).append("|");
        despues = despues.append(despuesEmpl.getIdEdoCivil()).append("|");
        despues = despues.append(despuesEmpl.getEMailOficial()).append("|");
        despues = despues.append(despuesEmpl.getEMailPersonal()).append("|");
        despues = despues.append(despuesEmpl.getIdEdoNac()).append("|");
        despues = despues.append(despuesEmpl.getIdGenero()).append("|");
        despues = despues.append(despuesEmpl.getIdNacionalidad()).append("|");
        despues = despues.append(despuesEmpl.getDiscapacidad()).append("|");
        despues = despues.append(despuesEmpl.getIdNivelEscolar()).append("|");
        despues = despues.append(despuesEmpl.getIdProfnCarrera()).append("|");
        despues = despues.append(despuesEmpl.getIdInstEducativa()).append("|");
        despues = despues.append(despuesEmpl.getIdInstProtcivil()).append("|");
        despues = despues.append(despuesEmpl.getIdEspProtCivil()).append("|");
        despues = despues.append(despuesEmpl.getEstudiaSiNo()).append("|");
        despues = despues.append(despuesEmpl.getPadreMadre()).append("|");
        despues = despues.append(despuesEmpl.getTerminoCargoSind()).append("|");
        despues = despues.append(despuesEmpl.getCompatEmpleo()).append("|");
        despues = despues.append(despuesEmpl.getIdRusp()).append("|");
        despues = despues.append(despuesEmpl.getFecNotDecPatr()).append("|");
        despues = despues.append(despuesEmpl.getFecIniDeclPatr()).append("|");
        despues = despues.append(despuesEmpl.getFecIngSpc()).append("|");
        despues = despues.append(despuesEmpl.getUsuario()).append("|");
        despues = despues.append(despuesEmpl.getFecModifico());
        
        heads = heads.append("RFC_EMPLEADO").append("|");
        heads = heads.append("RFC_UNICO").append("|");
        heads = heads.append("ID_ULTIMO_MOVTO").append("|");
        heads = heads.append("FEC_ULTIMO_MOVTO").append("|");
        heads = heads.append("ID_BANCO_SAR").append("|");
        heads = heads.append("ID_TIPO_PAGO").append("|");
        heads = heads.append("IMSS_ISSSTE").append("|");
        heads = heads.append("NUM_ISSSTE").append("|");
        heads = heads.append("SISTEMA_REPARTO").append("|");
        heads = heads.append("CURP_EMPLEADO").append("|");
        heads = heads.append("NOMBRE_EMPLEADO").append("|");
        heads = heads.append("PRIMER_APELLIDO").append("|");
        heads = heads.append("SEGUNDO_APELLIDO").append("|");
        heads = heads.append("FEC_NACIMIENTO").append("|");
        heads = heads.append("CLABE_EMPLEADO").append("|");
        heads = heads.append("REFERENCIA_OFICIO").append("|");
        heads = heads.append("EMP_QNA_CAPTURA").append("|");
        heads = heads.append("INGRESO_GOB_FED").append("|");
        heads = heads.append("INGRESO_DEPENDENCIA").append("|");
        heads = heads.append("ID_PLAZA_VIGENTE").append("|");
        heads = heads.append("CASO_MUESTRA").append("|");
        heads = heads.append("CALLE_PARTICULAR").append("|");
        heads = heads.append("COLONIA_PARTICULAR").append("|");
        heads = heads.append("ID_MUNI_PARTICULAR").append("|");
        heads = heads.append("ID_EDO_PARTICULAR").append("|");
        heads = heads.append("CODPOST_PARTICULAR").append("|");
        heads = heads.append("TEL_PARTICULAR").append("|");
        heads = heads.append("ID_EDO_CIVIL").append("|");
        heads = heads.append("E_MAIL_OFICIAL").append("|");
        heads = heads.append("E_MAIL_PERSONAL").append("|");
        heads = heads.append("ID_EDO_NAC").append("|");
        heads = heads.append("ID_GENERO").append("|");
        heads = heads.append("ID_NACIONALIDAD").append("|");
        heads = heads.append("DISCAPACIDAD").append("|");
        heads = heads.append("ID_NIVEL_ESCOLAR").append("|");
        heads = heads.append("ID_PROFN_CARRERA").append("|");
        heads = heads.append("ID_INST_EDUCATIVA").append("|");
        heads = heads.append("ID_INST_PROTCIVIL").append("|");
        heads = heads.append("ID_ESP_PROT_CIVIL").append("|");
        heads = heads.append("ESTUDIA_SI_NO").append("|");
        heads = heads.append("PADRE_MADRE").append("|");
        heads = heads.append("TERMINO_CARGO_SIND").append("|");
        heads = heads.append("COMPAT_EMPLEO").append("|");
        heads = heads.append("ID_RUSP").append("|");
        heads = heads.append("FEC_NOT_DEC_PATR").append("|");
        heads = heads.append("FEC_INI_DECL_PATR").append("|");
        heads = heads.append("FEC_ING_SPC").append("|");
        heads = heads.append("USUARIO").append("|");
        heads = heads.append("FEC_MODIFICO");
        
        Integer secuencia = super.persistence().get(QueryTdBitacoraUpdateTablaDAO.class).getSequenceTdBitacoraTabla().get(0).getIdBitacora();
        TdBitacoraUpdateTabla tdBitacoraTabla = new TdBitacoraUpdateTabla(secuencia, despues.toString(), antes.toString(), heads.toString(), ip, tablaDTO.getMotivoModifica(), "TD_EMPLEADO");
        super.persistence().get(TdBitacoraUpdateTablaDAO.class).save(tdBitacoraTabla);
    }
}
