// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package gob.shcp.sireh.ws;

import java.util.Collection;

public class Dept {

    int id;
    String name;
    String location;
    Collection<Emp> employees;

    public Dept() {
    }

    public Dept(int id, String name, String location, Collection<Emp> employees) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.employees = employees;
    }

    public java.lang.String getLocation() {
        return location;
    }

    public void setLocation(java.lang.String location) {
        this.location = location;
    }

    public java.lang.String getName() {
        return name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setEmployees(Collection<Emp> employees) {
        this.employees = employees;
    }

    public Collection<Emp> getEmployees() {
        return employees;
    }

    public String toString(Dept dept) {
        return dept.getId() + "," + dept.getName() + "," + dept.getLocation() + "," + dept.getEmployees();
    }
}
