// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package gob.shcp.sireh.ws;

public interface MyWebService2 extends java.rmi.Remote {
    public gob.shcp.sireh.ws.Dept getDeptInfo(int parameters) throws 
         java.rmi.RemoteException;
    public java.lang.String getDeptInfoString(int parameters) throws 
         java.rmi.RemoteException;
}
